export const ttdColumnsHeaderMap = {
  number: 'Номер',
  player: 'Игрок',
  position: 'Позиция',
  minutesPlayed: 'Минут',
  goals: 'Голы',
  assists: 'Голевые передачи',
  keyPasses: 'Ключевые передачи',
  keyPassesSuccess: 'Ключевые передачи+',
  'keyPassesSuccess%': 'Ключевые передачи%',
  shoots: 'Удары',
  shoots_OnTarget: 'Удары в створ',
  'shoots_OnTarget%': 'Удары в створ%',
  xG: 'xG',
  fouls: 'Фолы',
  foulsOnPlayer: 'Фолы на игроке',
  offside: 'Офсайды',
  yellowCards: 'Желтые карточки',
  redCards: 'Красные карточки',
  actions: 'Действия',
  actionsSuccess: 'Удачные действия',
  'actionsSuccess%': 'Удачные действия%',
  actionsInsideBox: 'Действия в штрафной',
  chances: 'Голевые моменты',
  chancesSuccess: 'Голевые моменты+',
  'chancesSuccess%': 'Голевые моменты%',
  lostBalls: 'Потери',
  lostBalls_OwnHalf: 'Потери на своей половине',
  ballRecoveries: 'Отборы мяча',
  ballRecoveries_OppositeHalf: 'Отборы на половине соперника',
  badBallControl: 'Неудачные обработки мяча',
  passes: 'Передачи',
  passesSuccess: 'Передачи+',
  'passesSuccess%': 'Передачи+%',
  passForward: 'Передачи вперед',
  passForwardSuccess: 'Передачи вперед+',
  'passForwardSuccess%': 'Передачи вперед+%',
  passBack: 'Передачи назад',
  passBackSuccess: 'Передачи назад+',
  'passBackSuccess%': 'Передачи назад+%',
  passLong: 'Длинные передачи',
  passLongSuccess: 'Длинные передачи+',
  'passLongSuccess%': 'Длинные передачи+%',
  passShorMedium: 'Короткие, средние передачи',
  passShorMediumSuccess: 'Короткие, средние передачи+',
  'passShorMediumSuccess%': 'Короткие, средние передачи+%',
  passInsideFinalThird: 'Передачи в финальную треть',
  passInsideFinalThirdSuccess: 'Передачи в финальную треть+',
  'passInsideFinalThirdSuccess%': 'Передачи в финальную треть+%',
  passInsideBox: 'Передачи в штрафную',
  passInsideBoxSuccess: 'Передачи в штрафную+',
  'passInsideBoxSuccess%': 'Передачи в штрафную+%',
  crosses: 'Навесы',
  crossesSuccess: 'Навесы+',
  'crossesSuccess%': 'Навесы+%',
  shotAssists: 'Передачи под удар',
  shotAssistsSuccess: 'Передачи под удар+',
  'shotAssistsSuccess%': 'Передачи под удар+%',
  passesReceived: 'Передач получено',
  passesReceivedInsideBox: 'Передачи получено в штрафной',
  challenges: 'Единоборства',
  challengesSuccess: 'Единоборства+',
  'challengesSuccess%': 'Единоборства+%',
  aerialDuels: 'Единоборства вверху',
  aerialDuelsSuccess: 'Единоборства вверху+',
  'aerialDuelsSuccess%': 'Единоборства вверху+%',
  challengesInDefence: 'Единоборства в обороне',
  challengesInDefenceSuccess: 'Единоборства в обороне+',
  'challengesInDefenceSuccess%': 'Единоборства в обороне+%',
  challengesInAttack: 'Единоборства в атаке',
  challengesInAttackSuccess: 'Единоборства в атаке+',
  'challengesInAttackSuccess%': 'Единоборства в атаке+%',
  dribbles: 'Обводки',
  dribblesSuccess: 'Обводки+',
  'dribblesSuccess%': 'Обводки+%',
  tackles: 'Отборы',
  tacklesSuccess: 'Отборы+',
  'tacklesSuccess%': 'Отборы+%',
  interceptions: 'Перехваты',
  freeKick: 'Штрафные',
  freeKickShoots: 'Удары со штрафных',
  freeKickShootsOnTarget: 'Удары со штрафных в створ',
  'freeKickShootsOnTarget%': 'Удары со штрафных в створ%',
  corners: 'Угловые',
  throwIns: 'Ауты',
  throwInSuccess: 'Ауты+',
  'throwInSuccess%': 'Ауты+%',
};

export const ttdShorColumnsHeaderMap = {
  number: '№',
  player: 'Игрок',
  position: 'Позиция',
  minutesPlayed: 'МИН',
  goals: 'Г',
  assists: 'ГП',
  keyPasses: 'КП',
  keyPassesSuccess: 'КП+',
  'keyPassesSuccess%': 'КП%',
  shoots: 'УД',
  shoots_OnTarget: 'УД+',
  'shoots_OnTarget%': 'УД%',
  xG: 'xG',
  fouls: 'Ф',
  foulsOnPlayer: 'ФП',
  offside: 'ОФ',
  yellowCards: 'ЖК',
  redCards: 'КК',
  actions: 'ТТД',
  actionsSuccess: 'ТТД+',
  'actionsSuccess%': 'ТТД%',
  actionsInsideBox: 'ТШ',
  chances: 'ГМ',
  chancesSuccess: 'ГМ+',
  'chancesSuccess%': 'ГМ%',
  lostBalls: 'ПОТ',
  lostBalls_OwnHalf: 'ПТС',
  ballRecoveries: 'ВОЗ',
  ballRecoveries_OppositeHalf: 'ВЗС',
  badBallControl: 'НОМ',
  passes: 'ПАС',
  passesSuccess: 'ПАС+',
  'passesSuccess%': 'ПАС%',
  passForward: 'ПСВ',
  passForwardSuccess: 'ПСВ+',
  'passForwardSuccess%': 'ПСВ%',
  passBack: 'ПCН',
  passBackSuccess: 'ПCН+',
  'passBackSuccess%': 'ПCН%',
  passLong: 'ДПС',
  passLongSuccess: 'ДПС+',
  'passLongSuccess%': 'ДПС%',
  passShorMedium: 'КСП',
  passShorMediumSuccess: 'КСП+',
  'passShorMediumSuccess%': 'КСП%',
  passInsideFinalThird: 'ПФТ',
  passInsideFinalThirdSuccess: 'ПФТ+',
  'passInsideFinalThirdSuccess%': 'ПФТ%',
  passInsideBox: 'ПСШ',
  passInsideBoxSuccess: 'ПСШ+',
  'passInsideBoxSuccess%': 'ПСШ%',
  crosses: 'НАВ',
  crossesSuccess: 'НАВ+',
  'crossesSuccess%': 'НАВ%',
  shotAssists: 'ППУ',
  shotAssistsSuccess: 'ППУ+',
  'shotAssistsSuccess%': 'ППУ%',
  passesReceived: 'ППС',
  passesReceivedInsideBox: 'ППШ',
  challenges: 'ЕД',
  challengesSuccess: 'ЕД+',
  'challengesSuccess%': 'ЕД%',
  aerialDuels: 'ЕДВ',
  aerialDuelsSuccess: 'ЕДВ+',
  'aerialDuelsSuccess%': 'ЕДВ%',
  challengesInDefence: 'ЕДО',
  challengesInDefenceSuccess: 'ЕДО+',
  'challengesInDefenceSuccess%': 'ЕДО%',
  challengesInAttack: 'ЕДА',
  challengesInAttackSuccess: 'ЕДА+',
  'challengesInAttackSuccess%': 'ЕДА%',
  dribbles: 'ОБВ',
  dribblesSuccess: 'ОБВ+',
  'dribblesSuccess%': 'ОБВ%',
  tackles: 'ОТБ',
  tacklesSuccess: 'ОТБ+',
  'tacklesSuccess%': 'ОТБ%',
  interceptions: 'ПХ',
  freeKick: 'ШТУ',
  freeKickShoots: 'ПШУ',
  freeKickShootsOnTarget: 'ПШУ+',
  'freeKickShootsOnTarget%': 'ПШУ%',
  corners: 'УГЛ',
  throwIns: 'АУТ',
  throwInSuccess: 'АУТ+',
  'throwInSuccess%': 'АУТ%',
};
