-- CreateTable
CREATE TABLE "session" (
    "id" TEXT NOT NULL,
    "gpexe_id" INTEGER,
    "category_name" VARCHAR(255),
    "start_timestamp" TIMESTAMP(3) NOT NULL,
    "total_time" INTEGER,
    "name" VARCHAR(255),
    "end_timestamp" TIMESTAMP(3),
    "notes" VARCHAR(255),
    "team_id" INTEGER,
    "n_tracks" INTEGER,
    "average_time" DOUBLE PRECISION,
    "total_distance" DOUBLE PRECISION,
    "average_v" DOUBLE PRECISION,
    "athletesessionspeedzone_distance_1" DOUBLE PRECISION,
    "athletesessionspeedzone_distance_2" DOUBLE PRECISION,
    "athletesessionspeedzone_distance_3" DOUBLE PRECISION,
    "athletesessionspeedzone_distance_4" DOUBLE PRECISION,
    "athletesessionspeedzone_distance_5" DOUBLE PRECISION,
    "max_values_speed" DOUBLE PRECISION,
    "speed_events" INTEGER,
    "tot_burst_events" INTEGER,
    "tot_brake_events" INTEGER,
    "eccentric_index" DOUBLE PRECISION,
    "athletesessionpowerzone_distance_1" DOUBLE PRECISION,
    "athletesessionpowerzone_distance_2" DOUBLE PRECISION,
    "athletesessionpowerzone_distance_3" DOUBLE PRECISION,
    "average_p" DOUBLE PRECISION,
    "max_values_power" DOUBLE PRECISION,
    "equivalent_distance_index" DOUBLE PRECISION,
    "equivalent_distance" DOUBLE PRECISION,
    "total_energy" DOUBLE PRECISION,
    "anaerobic_energy" DOUBLE PRECISION,
    "anaerobic_index" DOUBLE PRECISION,
    "aerobic_ratio" DOUBLE PRECISION,
    "average_power_aer" DOUBLE PRECISION,
    "power_events" INTEGER,
    "power_events_avg_time" DOUBLE PRECISION,
    "power_events_avg_power" DOUBLE PRECISION,
    "recovery_average_time" DOUBLE PRECISION,
    "recovery_average_power" DOUBLE PRECISION,
    "athletesessionpowereventdurationzone_events_1" INTEGER,
    "athletesessionpowereventdurationzone_events_2" INTEGER,
    "athletesessionpowereventdurationzone_events_3" INTEGER,
    "athletesessionpowereventdistancezone_events_1" INTEGER,
    "athletesessionpowereventdistancezone_events_2" INTEGER,
    "athletesessionpowereventdistancezone_events_3" INTEGER,
    "athletesessionpowereventmaxspeedzone_events_1" INTEGER,
    "athletesessionpowereventmaxspeedzone_events_2" INTEGER,
    "athletesessionpowereventmaxspeedzone_events_3" INTEGER,
    "external_work" DOUBLE PRECISION,
    "ext_work_over" DOUBLE PRECISION,
    "ext_work_over_neg" DOUBLE PRECISION,
    "average_external_power" DOUBLE PRECISION,
    "ext_work_over_zone0" DOUBLE PRECISION,
    "ext_work_over_zone1" DOUBLE PRECISION,
    "ext_work_over_zone2" DOUBLE PRECISION,
    "ext_work_over_zone0_neg" DOUBLE PRECISION,
    "ext_work_over_zone1_neg" DOUBLE PRECISION,
    "ext_work_over_zone2_neg" DOUBLE PRECISION,
    "average_hr" DOUBLE PRECISION,
    "average_hr_percentual" DOUBLE PRECISION,
    "max_values_cardio" DOUBLE PRECISION,
    "max_values_cardio_percentual" DOUBLE PRECISION,
    "athletesessionheartratezone_time_2" DOUBLE PRECISION,
    "athletesessionheartratezone_time_3" DOUBLE PRECISION,
    "athletesessionheartratezone_time_4" DOUBLE PRECISION,

    CONSTRAINT "session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "athlete_session" (
    "id" TEXT NOT NULL,
    "gpexe_id" INTEGER,
    "athlete_id" TEXT NOT NULL,
    "session_id" TEXT NOT NULL,
    "average_time" DOUBLE PRECISION,
    "total_distance" DOUBLE PRECISION,
    "average_v" DOUBLE PRECISION,
    "athletesessionspeedzone_distance_1" DOUBLE PRECISION,
    "athletesessionspeedzone_distance_2" DOUBLE PRECISION,
    "athletesessionspeedzone_distance_3" DOUBLE PRECISION,
    "athletesessionspeedzone_distance_4" DOUBLE PRECISION,
    "athletesessionspeedzone_distance_5" DOUBLE PRECISION,
    "max_values_speed" DOUBLE PRECISION,
    "speed_events" INTEGER,
    "tot_burst_events" INTEGER,
    "tot_brake_events" INTEGER,
    "eccentric_index" DOUBLE PRECISION,
    "athletesessionpowerzone_distance_1" DOUBLE PRECISION,
    "athletesessionpowerzone_distance_2" DOUBLE PRECISION,
    "athletesessionpowerzone_distance_3" DOUBLE PRECISION,
    "average_p" DOUBLE PRECISION,
    "max_values_power" DOUBLE PRECISION,
    "equivalent_distance_index" DOUBLE PRECISION,
    "equivalent_distance" DOUBLE PRECISION,
    "total_energy" DOUBLE PRECISION,
    "anaerobic_energy" DOUBLE PRECISION,
    "anaerobic_index" DOUBLE PRECISION,
    "aerobic_ratio" DOUBLE PRECISION,
    "average_power_aer" DOUBLE PRECISION,
    "power_events" INTEGER,
    "power_events_avg_time" DOUBLE PRECISION,
    "power_events_avg_power" DOUBLE PRECISION,
    "recovery_average_time" DOUBLE PRECISION,
    "recovery_average_power" DOUBLE PRECISION,
    "athletesessionpowereventdurationzone_events_1" INTEGER,
    "athletesessionpowereventdurationzone_events_2" INTEGER,
    "athletesessionpowereventdurationzone_events_3" INTEGER,
    "athletesessionpowereventdistancezone_events_1" INTEGER,
    "athletesessionpowereventdistancezone_events_2" INTEGER,
    "athletesessionpowereventdistancezone_events_3" INTEGER,
    "athletesessionpowereventmaxspeedzone_events_1" INTEGER,
    "athletesessionpowereventmaxspeedzone_events_2" INTEGER,
    "athletesessionpowereventmaxspeedzone_events_3" INTEGER,
    "external_work" DOUBLE PRECISION,
    "ext_work_over" DOUBLE PRECISION,
    "ext_work_over_neg" DOUBLE PRECISION,
    "average_external_power" DOUBLE PRECISION,
    "ext_work_over_zone0" DOUBLE PRECISION,
    "ext_work_over_zone1" DOUBLE PRECISION,
    "ext_work_over_zone2" DOUBLE PRECISION,
    "ext_work_over_zone0_neg" DOUBLE PRECISION,
    "ext_work_over_zone1_neg" DOUBLE PRECISION,
    "ext_work_over_zone2_neg" DOUBLE PRECISION,
    "average_hr" DOUBLE PRECISION,
    "average_hr_percentual" DOUBLE PRECISION,
    "max_values_cardio" DOUBLE PRECISION,
    "max_values_cardio_percentual" DOUBLE PRECISION,
    "athletesessionheartratezone_time_2" DOUBLE PRECISION,
    "athletesessionheartratezone_time_3" DOUBLE PRECISION,
    "athletesessionheartratezone_time_4" DOUBLE PRECISION,

    CONSTRAINT "athlete_session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "athlete" (
    "id" TEXT NOT NULL,
    "name" TEXT,
    "isInTeam" BOOLEAN NOT NULL DEFAULT false,
    "isInjured" BOOLEAN NOT NULL DEFAULT false,
    "number" INTEGER,
    "birthday" TIMESTAMP(3),
    "height" INTEGER,
    "photo" TEXT,
    "weight" DOUBLE PRECISION,
    "foot" TEXT,
    "last_name" TEXT,
    "first_name" TEXT,
    "short_name" TEXT,
    "position_id" TEXT,
    "gpexe_id" INTEGER NOT NULL,

    CONSTRAINT "athlete_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "position" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,

    CONSTRAINT "position_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "game" (
    "id" TEXT NOT NULL,
    "date" TIMESTAMP(3),
    "vs" TEXT,
    "competition" TEXT,
    "result" TEXT,
    "home" BOOLEAN,
    "total_distance" DOUBLE PRECISION,
    "speedzone4_distance" DOUBLE PRECISION,
    "speedzone5_distance" DOUBLE PRECISION,
    "avg_speed" DOUBLE PRECISION,
    "minutesPlayed" INTEGER,
    "goals" INTEGER,
    "assists" INTEGER,
    "keyPasses" INTEGER,
    "keyPassesSuccess" INTEGER,
    "keyPassesSuccess_pct" TEXT,
    "shoots" INTEGER,
    "shoots_OnTarget" INTEGER,
    "shoots_OnTarget_pct" TEXT,
    "xG" INTEGER,
    "fouls" INTEGER,
    "foulsOnPlayer" INTEGER,
    "offside" INTEGER,
    "yellowCards" INTEGER,
    "redCards" INTEGER,
    "actions" INTEGER,
    "actionsSuccess" INTEGER,
    "actionsSuccess_pct" TEXT,
    "actionsInsideBox" INTEGER,
    "chances" INTEGER,
    "chancesSuccess" INTEGER,
    "chancesSuccess_pct" TEXT,
    "lostBalls" INTEGER,
    "lostBalls_OwnHalf" INTEGER,
    "ballRecoveries" INTEGER,
    "ballRecoveries_OppositeHalf" INTEGER,
    "badBallControl" INTEGER,
    "passes" INTEGER,
    "passesSuccess" INTEGER,
    "passesSuccess_pct" TEXT,
    "passForward" INTEGER,
    "passForwardSuccess" INTEGER,
    "passForwardSuccess_pct" TEXT,
    "passBack" INTEGER,
    "passBackSuccess" INTEGER,
    "passBackSuccess_pct" TEXT,
    "passLong" INTEGER,
    "passLongSuccess" INTEGER,
    "passLongSuccess_pct" TEXT,
    "passShorMedium" INTEGER,
    "passShorMediumSuccess" INTEGER,
    "passShorMediumSuccess_pct" TEXT,
    "passInsideFinalThird" INTEGER,
    "passInsideFinalThirdSuccess" INTEGER,
    "passInsideFinalThirdSuccess_pct" TEXT,
    "passInsideBox" INTEGER,
    "passInsideBoxSuccess" INTEGER,
    "passInsideBoxSuccess_pct" TEXT,
    "crosses" INTEGER,
    "crossesSuccess" INTEGER,
    "crossesSuccess_pct" TEXT,
    "shotAssists" INTEGER,
    "shotAssistsSuccess" INTEGER,
    "shotAssistsSuccess_pct" TEXT,
    "passesReceived" INTEGER,
    "passesReceivedInsideBox" INTEGER,
    "challenges" INTEGER,
    "challengesSuccess" INTEGER,
    "challengesSuccess_pct" TEXT,
    "aerialDuels" INTEGER,
    "aerialDuelsSuccess" INTEGER,
    "aerialDuelsSuccess_pct" TEXT,
    "challengesInDefence" INTEGER,
    "challengesInDefenceSuccess" INTEGER,
    "challengesInDefenceSuccess_pct" TEXT,
    "challengesInAttack" INTEGER,
    "challengesInAttackSuccess" INTEGER,
    "challengesInAttackSuccess_pct" TEXT,
    "dribbles" INTEGER,
    "dribblesSuccess" INTEGER,
    "dribblesSuccess_pct" TEXT,
    "tackles" INTEGER,
    "tacklesSuccess" INTEGER,
    "tacklesSuccess_pct" TEXT,
    "interceptions" INTEGER,
    "freeKick" INTEGER,
    "freeKickShoots" INTEGER,
    "freeKickShootsOnTarget" INTEGER,
    "freeKickShootsOnTarget_pct" TEXT,
    "corners" INTEGER,
    "throwIns" INTEGER,
    "throwInSuccess" INTEGER,
    "throwInSuccess_pct" TEXT,

    CONSTRAINT "game_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "athlete_game_fitness" (
    "id" TEXT NOT NULL,
    "athlete_id" TEXT,
    "game_id" TEXT NOT NULL,
    "number" INTEGER NOT NULL,
    "minutes" INTEGER NOT NULL,
    "total_distance" DOUBLE PRECISION,
    "speedzone4_distance" DOUBLE PRECISION,
    "speedzone5_distance" DOUBLE PRECISION,
    "avg_speed" DOUBLE PRECISION,

    CONSTRAINT "athlete_game_fitness_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "athlete_game_ttd" (
    "id" TEXT NOT NULL,
    "athlete_id" TEXT,
    "game_id" TEXT NOT NULL,
    "number" INTEGER,
    "minutesPlayed" INTEGER,
    "goals" INTEGER,
    "assists" INTEGER,
    "keyPasses" INTEGER,
    "keyPassesSuccess" INTEGER,
    "keyPassesSuccess_pct" TEXT,
    "shoots" INTEGER,
    "shoots_OnTarget" INTEGER,
    "shoots_OnTarget_pct" TEXT,
    "xG" INTEGER,
    "fouls" INTEGER,
    "foulsOnPlayer" INTEGER,
    "offside" INTEGER,
    "yellowCards" INTEGER,
    "redCards" INTEGER,
    "actions" INTEGER,
    "actionsSuccess" INTEGER,
    "actionsSuccess_pct" TEXT,
    "actionsInsideBox" INTEGER,
    "chances" INTEGER,
    "chancesSuccess" INTEGER,
    "chancesSuccess_pct" TEXT,
    "lostBalls" INTEGER,
    "lostBalls_OwnHalf" INTEGER,
    "ballRecoveries" INTEGER,
    "ballRecoveries_OppositeHalf" INTEGER,
    "badBallControl" INTEGER,
    "passes" INTEGER,
    "passesSuccess" INTEGER,
    "passesSuccess_pct" TEXT,
    "passForward" INTEGER,
    "passForwardSuccess" INTEGER,
    "passForwardSuccess_pct" TEXT,
    "passBack" INTEGER,
    "passBackSuccess" INTEGER,
    "passBackSuccess_pct" TEXT,
    "passLong" INTEGER,
    "passLongSuccess" INTEGER,
    "passLongSuccess_pct" TEXT,
    "passShorMedium" INTEGER,
    "passShorMediumSuccess" INTEGER,
    "passShorMediumSuccess_pct" TEXT,
    "passInsideFinalThird" INTEGER,
    "passInsideFinalThirdSuccess" INTEGER,
    "passInsideFinalThirdSuccess_pct" TEXT,
    "passInsideBox" INTEGER,
    "passInsideBoxSuccess" INTEGER,
    "passInsideBoxSuccess_pct" TEXT,
    "crosses" INTEGER,
    "crossesSuccess" INTEGER,
    "crossesSuccess_pct" TEXT,
    "shotAssists" INTEGER,
    "shotAssistsSuccess" INTEGER,
    "shotAssistsSuccess_pct" TEXT,
    "passesReceived" INTEGER,
    "passesReceivedInsideBox" INTEGER,
    "challenges" INTEGER,
    "challengesSuccess" INTEGER,
    "challengesSuccess_pct" TEXT,
    "aerialDuels" INTEGER,
    "aerialDuelsSuccess" INTEGER,
    "aerialDuelsSuccess_pct" TEXT,
    "challengesInDefence" INTEGER,
    "challengesInDefenceSuccess" INTEGER,
    "challengesInDefenceSuccess_pct" TEXT,
    "challengesInAttack" INTEGER,
    "challengesInAttackSuccess" INTEGER,
    "challengesInAttackSuccess_pct" TEXT,
    "dribbles" INTEGER,
    "dribblesSuccess" INTEGER,
    "dribblesSuccess_pct" TEXT,
    "tackles" INTEGER,
    "tacklesSuccess" INTEGER,
    "tacklesSuccess_pct" TEXT,
    "interceptions" INTEGER,
    "freeKick" INTEGER,
    "freeKickShoots" INTEGER,
    "freeKickShootsOnTarget" INTEGER,
    "freeKickShootsOnTarget_pct" TEXT,
    "corners" INTEGER,
    "throwIns" INTEGER,
    "throwInSuccess" INTEGER,
    "throwInSuccess_pct" TEXT,

    CONSTRAINT "athlete_game_ttd_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "injury" (
    "id" TEXT NOT NULL,
    "start_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "end_date" TIMESTAMP(3),
    "place" TEXT,
    "diagnosis" TEXT,
    "estimated_recovery" TEXT,
    "athlete_id" TEXT NOT NULL,

    CONSTRAINT "injury_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "session_gpexe_id_key" ON "session"("gpexe_id");

-- CreateIndex
CREATE UNIQUE INDEX "athlete_session_gpexe_id_key" ON "athlete_session"("gpexe_id");

-- CreateIndex
CREATE UNIQUE INDEX "athlete_gpexe_id_key" ON "athlete"("gpexe_id");

-- AddForeignKey
ALTER TABLE "athlete_session" ADD CONSTRAINT "athlete_session_athlete_id_fkey" FOREIGN KEY ("athlete_id") REFERENCES "athlete"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "athlete_session" ADD CONSTRAINT "athlete_session_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "session"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "athlete" ADD CONSTRAINT "athlete_position_id_fkey" FOREIGN KEY ("position_id") REFERENCES "position"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "athlete_game_fitness" ADD CONSTRAINT "athlete_game_fitness_athlete_id_fkey" FOREIGN KEY ("athlete_id") REFERENCES "athlete"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "athlete_game_fitness" ADD CONSTRAINT "athlete_game_fitness_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "athlete_game_ttd" ADD CONSTRAINT "athlete_game_ttd_athlete_id_fkey" FOREIGN KEY ("athlete_id") REFERENCES "athlete"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "athlete_game_ttd" ADD CONSTRAINT "athlete_game_ttd_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "injury" ADD CONSTRAINT "injury_athlete_id_fkey" FOREIGN KEY ("athlete_id") REFERENCES "athlete"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
